//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole.AppData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class Eleve : INotifyPropertyChanged
    {
        public int id;
        public int Id
        {
            get { return id; }
            set
            {
                id = value;
                NotifyPropertyChanged("Id");
            }
        }


        public string nom;
        public string Nom
        {
            get { return nom; }
            set
            {
                nom = value;
                NotifyPropertyChanged("Nom");
            }
        }
        public string prenom;
        public string Prenom
        {
            get { return prenom; }
            set
            {
                prenom = value;
                NotifyPropertyChanged("Prenom");
            }
        }

        public Nullable<int> creditHoraire;
        public Nullable<int> CreditHoraire  
        {
            get { return creditHoraire; }
            set
            {
                creditHoraire = value;
                NotifyPropertyChanged("Prenom");
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;

        public void NotifyPropertyChanged(string nomPropriete)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(nomPropriete));
        }
    }
}
